/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouletteRouteImport } from './routes/roulette'
import { Route as FlipCoinRouteImport } from './routes/flip-coin'
import { Route as IndexRouteImport } from './routes/index'

const RouletteRoute = RouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const FlipCoinRoute = FlipCoinRouteImport.update({
  id: '/flip-coin',
  path: '/flip-coin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flip-coin': typeof FlipCoinRoute
  '/roulette': typeof RouletteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flip-coin': typeof FlipCoinRoute
  '/roulette': typeof RouletteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flip-coin': typeof FlipCoinRoute
  '/roulette': typeof RouletteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flip-coin' | '/roulette'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flip-coin' | '/roulette'
  id: '__root__' | '/' | '/flip-coin' | '/roulette'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlipCoinRoute: typeof FlipCoinRoute
  RouletteRoute: typeof RouletteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roulette': {
      id: '/roulette'
      path: '/roulette'
      fullPath: '/roulette'
      preLoaderRoute: typeof RouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flip-coin': {
      id: '/flip-coin'
      path: '/flip-coin'
      fullPath: '/flip-coin'
      preLoaderRoute: typeof FlipCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlipCoinRoute: FlipCoinRoute,
  RouletteRoute: RouletteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
